This is a working summary of the paper 

# Abstract (p.0)

The Abstract of the paper gives general indications about where the paper wants to go : 

- What is the carbon footprint of capital ? What is its distribution ? 

To answer this question, they offer a new acounting framework that captures all emissions without double counting. 

Their results are : 

- This accounting framework underlies that the rich parts of the distributions are much more responsible of the emissions than in other accounting systems.
- For the very rich, most of their emissions stem from asset ownership, not from direct energy consumption. 
- Emissions from capital ownership is more concentrated than cpital itself. 

The implications at the policy-level are that targeting individual assets and investments should be promising to reduce CO_2 emissions.

# 1 Introduction (pp.1-4)

1. They identify an existing gap in the literature of carbon accounting : individuals as owners of polluting assets. Indeed, they underly that most of the existing literature focus on either the country level, or on the individual as final consumers, or finally on the corporate as producers. 

2. Most of the literature of carbon accounting focused on individuals have taken the consumer based approach. At the international level, this is interesting because it allows a study of why some countries have emissions that in fact are due to the living standard level of other countries. At the national level however, this is problematic because there is a clear problem in putting all the responsibility of the carbon emissions to the final consumer. 

3. They say that this article has 3 main goals : 

- Define 3 measures of individual carbon footprint including ownership-related emissions. 
- Apply those measure to France, Germany, and the USA. 
- Show stylized facts and discuss implications at the environmental and tax policies level.

4. The 3 approaches of measure of individual carbon footprint are : 

- owenrship-based approach : emissions from production are attributed to firm owners. 
- consumption-based approach : attribution to the final consumers. 
- mixed-based approach : emissions from production are attributed to consumers, except the ones du to capital formation (investment).

They say that in all approaches, direct emissions of Households are attributed to the Households themselves.

5. They combining official environmental accounts (i.e. air emissions) and national accounts (like production, income, and wealth) to compute the carbon distribution at the individual level for the 3 approaches.

6. With the distribution of asset ownership, they estimate the individual emissions of asset ownership, with "existing estimates from the literature on the distribution of direct and consumption-based emissions"(p.2). Essentially, they combine : 

- estimates of emissions
- asset ownership distribution 

To estimate individual emissions of asset ownership. 

8. Using this approach, they find important emissions inequalities. When using the ownership-based approach, the rich are much more responsible of emissions (increase by 2 to 2.8 timefolds). 

9. Also, they find that the majority of emissions of the wealthiest come from their asset, and not from their consumption. 

10. They also note a higher concentration of emissions from wealth ownership. In other words, the assets of the very rich have a higher emission intensity in average.

11. They conclude that a tax on wealth emissions would be more progressive than a tax on emissions of consumption.

Contributions to the literature : 

13. They claim that their accounting system is consistent with satellite environmental accounts and distributional national accounts. 

14. Also, they depart from the consumption-based literature and offer a framework for individuals such as owners and investors. 

15. THey claim to provide original data about emissions of types of assets, that are consistent with macroeconomics totals. 

::: {.callout-caution}
This claim seems to be huge. This would mean that not only do they have alternative to the GHG protocol data and Trucost EDX dataset, but that they are also macro consistent. 
:::

16. This consistent framework allows for policy-studies at a finer level. Notably, for the study incidence of carbon taxes.

::: {.callout-caution}
This claim seems to be huge. Together with estimates of leasticity of emissions with respect to tax, we could have a consistent model, comparable to a development of Diamond and Mirrlees (1971) but for carbon taxes.
:::

# 2 Related Literature (pp.4-10)

18. They announce to focus on the critiques of the "dominant consumption-centered approach" (p.4) of the current literature. 

## 2.1. Origins (pp.)

19. THey identify carbon footprint as a concept developed in the 2000s, and take the definition of the IPCC 2022 and of Wiedmann and Minx, 2008. They advance two ideal properties of a carbobn footprint measure framework : 

- comprehensiveness : the system should take into account direct and indirect emissions of economic activities. 
- exclusivity : the system should not have double-counting. 

20. They recall the importance of the individual carbon footprint concept. 

## 2.2. COnsumption-based approaches (pp.)

21. The authors advance that the underlying assumption of the consumption-based appraoches of the measure of carbon footprint is that "individuals express their preferences through consumption (...), thereby guiding resource allocation in the economy" (p.5).

22. They recall that consumers-centered approaches are relevant to highlight international life-style discrepancies. 

23. They underly the fact that British Petroleum (BP) was one of the first to push forward this concept of individual carbon footprint and remind that "other interests may have played a role" (p.6).

24. They also advance that the country-level studies of carbon footprint were a product of the extension of the consumption-centered approach. They mention the Léontieff method and the development of sectorial coefficients of pollution-per-currency-unit (send a message to Jonathan pour qu'il me file la référence de la critique de cet aspect des statistiques de Chancel). 

25. They remind a key finding of Chancel and Piketty (2015) : carbon inequalities rised within countries and declined across countries. 

## 2.3. Critique of the consumption-based approach (pp.6-7)

26-28. The authors advance that the consumption-based approach oversttes the weight of individual choices on the economy. For that, they advance : 

- Market failures, such as monopoly or the impossibility to get carbon-free products. 
- Markup in the prices, that make individual changes impossible due to budget constraints. 
- Information asymmetries (Akerlof, Rothschild... (p.6))
- Pollution from production does not only serve consumption, because decision power in the production process also fives utility to the producer. 

::: {.callout-caution}
The third reason seems to be more name dropping than anything else. The mentioned articles underly the presence of information asymmetry, but the text does not explain how the information asymmetry affects the carbon emissions. 
The fourth point could be interesting for a micro-foundation of the reasoning.
:::

## 2.4. Production-based approaches and methods of shared attribution (pp.7-)

29. To answer the shortcomings of the consumption-based approach, an alternative has been the production-based approach, that is centered around the emissions of producing firms.

30-32. The authors propose to go from firm emissions to individuals emissions by focusing on the individuals running the firm. 

33. The authors then mention the share attribution methods, that focus on dividing emissions across the members of the production chain depending on thei added value (the reference seems to be Lenzen et al., 2007), the rest being attributed to the consumer. An alternative would be to divide emission by economic surplus. Both methods split the emissions between producers and consumers. They mention that the main inconvenient of this approach is that it requires data at an aggregated level, which is excluded for individual investors. 

34. They also mention income-based carbon accounting, by linkning emissions of production to the income received by individuals that participate in the production process, either by working or having capital. They mention that to the best of their knowledge, only two studies of this sort exist (among which a pepr of Pottier p.9).

::: {.callout-warning}
This last approach seems very close to what they are doing, except that it does not seem to involve distributions and national accounting. 
:::

## 2.5. Carbon emissions of individual investment portfolios 

They here mention the GHG protocol and a similar initiative : the Partnership for Carbon Accounting Financials (PCAF). They however advance that : 

- There is no consensus in the way of carbon accounting. 
- These estimates are not macro-consistent. 

::: {.callout-warning}
I very much doubt the first point. 
The second point is what really matters in the article. 
:::

## 2.6. Distributional national and environmental accounts (pp.-10)

36-38 : The authors advance that micro-founded datasets about national accounts have known a good improvement in the recent years, notably with the Distributional National Accounts (DINA). At the same time, no micro-macro consistent data exist for environmental pollution. 
Therefore, they base themselves on the DINA framework to construct a micro-macro consistent dataset for income, wealth, and emissions. 

:::{.callout-warning}

My main concern here is that the usual critiques of the DINA framework could invalidate the data constructed on the DINA framework. 

Also, what do they exactly mean with micro-macro founded in this context ? Does it refer to the exclusivity criterium of the accounting system, defined in the 19 paragraph ? This confusion should be cleared. 

:::

# 3. Data Sources and Methodology (p.10)

39. Theu authors explain that this part has three sections : 

- Conceptual framework : 3 carbon footprint approaches. 
- Data sources 
- Methodology :
    - extended aggregate environmental and economic acounts,
    - distributional environmental accounts
 
 ::: {.callout-warning}

 They make a reference to the IPCC 2022. Is is the same as paragraph 19 ? 
  
:::

## 3.1. Conceptual framework : Three Carbon Footprint Approaches

40. THey develop 3 approahces : 

- ownership-based 
- consumption-based
- mixed-based 

They refer to Appendix I, section C1 for a more detailed definition of each approach. 

### Ownership-based approach 

41. In this approach, theyattribute all scope 1 emissions (i.e. all direct emissions) to the owners of the firm. 
Owning a firm can be done through holding corporate equity (in proportion with the share held among the total capital). 
Owning a firm can also be done directly, for example for self entrepreneur. 

42. This simple rule allows to "overcome" difficulties from the linkage of a stock (wealth) with flow (emissions). 
They link emissions to production, to cpital, to owner, that can be households, government, corporations, or abroad agents. 

43. They only take direct emissions to comply with the exclusivity criterium. Also, they only take into account money that gives ownership-rights, and not purely financial assets. 

44. DIrect households emissions are simply linked to the households in this method. 

45. When emissions are due to capital owned by the government, they still attribute them to individuals.
All emissions that are related to the health and education sectors are uniformly attributed to all citizen, and emissions from all other sectors are attributed proportionally to the income. 

46. If a firm is operating abroad, but the owner is from the country of interest, the emissions are linked to him in this ownership-based approach.

47. The authors then compare their approach with the GHG and PCAF protocol. THey identify two main differences : 

- First, the other initiatives attribute emissions to purely financial assets, in opposition to their approach. 
- Second, the other initiatives are not individual and exclusive. All emissions (direct and indirect) are attributed to one asset, and not one individual. 

:::{.callout-warning}
I am not sure about the PCAF, but the GHG protocol differenciates scope 1,2 and 3. 
In this sense, one could choose to select the scope 1 emissions only. 
I don't see how the GHG would not be exclusive then.
:::

48. Still comparing the GHG and PCAF to their approaches, the owerniship approach has the closest results to them. 

### Mixed-based approach 

49. In their mixed-based approach, the authors attribute capital formation emissions to investors (or owners) and the rest of emissions to consumers. 

50. They use this difference between money to produce and money invested to reproduce capital of the firms, partially because this differenciation is available in the national accounts. Also, while money to produce production is "demanded" by consumers, money invested is "demanded" by the firm. 

51. The authors mention that they use a multi-regional input-output model, in which they separate : 

- gross fixed capital formation emissions 
- final households emisions 
- government consumption emissions

::: {.callout-warning}
What is a "multi-refional input-output model" ?
:::

52. In this approach, more is attributed to the final consumers than in the previous approach. 
Also, for the government emissions, they use the same strategy as in the ownership approach. 

53. The authors make the distinction between net and gross capital formation. 
In the gross capital formation is included the replacement of machines, and the buying of new machines (the net capital formation). 
In other words, gross capital formation investment is the addition of the replacement and investment. 
The authors decide to attribute gross capital formation because only taking net would attribute the difference to the final consumers. 
Also, net and gross capital formation have different intensities, so this distinction is important for the results. 

:::{.callout-warning}
I am missing something in the paragraph 53.
:::

54-55. THe authors recall the existence of the value-added approach and of the income-based approach. THeir point is : 

- The value-added approach is too difficult to implement if we do not have an aggregate vision of data. 
- The income-based approach is sensitive to manipulation from the firm. It would be beneficial for the firm to for example delay profit flow, making the workers responsible for all its emissions instead of the owners.

### Consumption-based approach 

56. To see strengths and weaknesses of this approach, check paragraphs (21-28).

57. The authors warn that the ownership appraoch (1) and the consumption and mixed-based approaches (2) have different total emissions. Indeed, some are owners of foreign firms, and some consume from foreign firms. 

58. THe authors advance that those approaches are complementary to each other and do a paralel with studying social inequalities. one must not only study the differences in consumption, but also in income and wealth to understand these inequalities. 

## 3.2. Data sources 

### Wealth data 

60. For France and Germany, the authors take the Household Finance and COnsumption Survey (HFCS), which has the wealth distribution and the asset owned along this distribution. 
For the US, they use the Distributional National Accounts (DINA) data (Piketty et al., 2018). Those are micro-files that include tax, survey, and national accounts data. 

61. The authors mention that there exist a lot of problems with HFCS data, for example they do not take into account the wealth of the richest part of the distribution. In this sense, they do proceed to correction of the HFCS data. 

62. The corrections are essentially a re-weighting approach based on the distribution of the World Inequalitye Database (WID). They fix weights so that they get the same distribution as in the WID. They assume however that the HFCS has correct information about the holding of assets along the wealth distribution. 
They add that the DINA files do not require corrections. 

### Macroeconomic capital stock and balance sheet data

63. To get these data, they link emissions to industries, and then to institutional sectors (households, government, corporations, and foreign firms). To do so, they take data from Eurostat for France and Germany. For the USA, they take data from the OECD. 
For the three countries, they use : 

- Stock of fixed assets by industry and year. 
- Stock of fixed assets by institutional sector. 
- Stock of financial liabilities by institutional sector and year.

### Emissions data

64.
